<?php

namespace App\Services;

use App\Enums\DocumentStatus;
use App\Enums\MeetingStatus;
use App\Enums\NotificationStatus;
use App\Enums\PerformancePredicate;
use App\Enums\PerformanceStatus;
use App\Enums\ProjectStatus;
use App\Enums\ReportStatus;
use App\Enums\TaskStatus;
use App\Models\AnalyticsSnapshot;
use App\Models\Organization;
use App\Models\User;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

/**
 * AnalyticsService — daily KPI aggregation for the Executive Dashboard
 * (Phase 4, Sprint 19-20).
 *
 * All aggregation runs as efficient COUNT/AVG queries (never hydrating domain
 * models) and is ALWAYS pinned to an explicit organization_id, so a snapshot is
 * deterministic and tenant-scoped regardless of who triggers the daily job. The
 * global org scope is bypassed with withoutGlobalScopes() ONLY together with an
 * explicit ->where('organization_id', $org->id) — never to read across tenants.
 *
 * computeSnapshot() returns the metrics bundle; snapshot() upserts it (idempotent
 * per org+date+scope); current() is a live (non-persisted) compute for "today";
 * trend() returns a series for the charts; opdComparison() returns per-child-OPD
 * rows for the pemda heatmap (analytics.view.pemda only).
 */
class AnalyticsService
{
    /**
     * Terminal task statuses that are NOT "open" / cannot be overdue.
     *
     * @var array<int, string>
     */
    private const TASK_TERMINAL = [
        TaskStatus::COMPLETED->value,
        TaskStatus::CANCELLED->value,
        TaskStatus::CLOSED->value,
        TaskStatus::ARCHIVED->value,
    ];

    /**
     * Compute the aggregated KPI bundle for one organization on a given date.
     * Pure aggregates (COUNT/AVG) pinned to organization_id — deterministic given
     * the data and free of cross-tenant leakage.
     *
     * @return array<string, mixed>
     */
    public function computeSnapshot(Organization $org, Carbon $date): array
    {
        $orgId = $org->id;

        return [
            'tasks'         => $this->taskMetrics($orgId),
            'meetings'      => $this->meetingMetrics($orgId),
            'documents'     => $this->documentMetrics($orgId),
            'reports'       => $this->reportMetrics($orgId),
            'projects'      => $this->projectMetrics($orgId),
            'skp'           => $this->skpMetrics($orgId),
            'users'         => $this->userMetrics($orgId),
            'notifications' => $this->notificationMetrics($orgId),
            'computed_at'   => $date->toDateString(),
        ];
    }

    /**
     * Idempotent upsert of the snapshot row for org+date+scope. Running twice for
     * the same key updates the single row in place (never duplicates).
     */
    public function snapshot(Organization $org, Carbon $date, ?User $actor = null): AnalyticsSnapshot
    {
        $metrics = $this->computeSnapshot($org, $date);

        // Only `metrics` is in the values array — the ULID id is generated by
        // HasUlid on create and is NOT touched on update, so re-running keeps the
        // same row identity (true idempotency per org+date+scope).
        return AnalyticsSnapshot::withoutGlobalScopes()->updateOrCreate(
            [
                'organization_id' => $org->id,
                'snapshot_date'   => $date->toDateString(),
                'scope'           => 'organization',
            ],
            [
                'metrics' => $metrics,
            ],
        );
    }

    /**
     * Live (non-persisted) compute for "today", so the dashboard shows fresh
     * numbers even before the nightly job has run.
     *
     * @return array<string, mixed>
     */
    public function current(Organization $org): array
    {
        return $this->computeSnapshot($org, Carbon::today());
    }

    /**
     * Persisted snapshot series for the charts: the most recent $days snapshots
     * (oldest → newest) reduced to the key metrics each chart needs.
     *
     * @return array<int, array<string, mixed>>
     */
    public function trend(Organization $org, int $days = 30): array
    {
        $since = Carbon::today()->subDays(max(1, $days) - 1)->toDateString();

        return AnalyticsSnapshot::withoutGlobalScopes()
            ->where('organization_id', $org->id)
            ->where('scope', 'organization')
            ->where('snapshot_date', '>=', $since)
            ->orderBy('snapshot_date')
            ->get()
            ->map(function (AnalyticsSnapshot $s) {
                $m = $s->metrics;

                return [
                    'date'            => $s->snapshot_date->toDateString(),
                    'completion_rate' => (float) ($m['tasks']['completion_rate'] ?? 0),
                    'tasks_completed' => (int) ($m['tasks']['completed'] ?? 0),
                    'tasks_overdue'   => (int) ($m['tasks']['overdue'] ?? 0),
                    'avg_skp'         => (float) ($m['skp']['avg_final_score'] ?? 0),
                    'active_projects' => (int) ($m['projects']['active'] ?? 0),
                ];
            })
            ->values()
            ->all();
    }

    /**
     * Per-child-OPD KPI rows for the pemda heatmap. Scoped to the pemda's children
     * (organizations whose pemda_id is the given pemda). Caller MUST already have
     * authorized analytics.view.pemda.
     *
     * @return array<int, array<string, mixed>>
     */
    public function opdComparison(Organization $pemda): array
    {
        $children = Organization::withoutGlobalScopes()
            ->where('pemda_id', $pemda->id)
            ->orderBy('name')
            ->get(['id', 'name', 'short_name', 'code']);

        return $children->map(function (Organization $opd) {
            $tasks = $this->taskMetrics($opd->id);
            $skp   = $this->skpMetrics($opd->id);
            $proj  = $this->projectMetrics($opd->id);

            return [
                'organization_id' => $opd->id,
                'name'            => $opd->short_name ?: $opd->name,
                'code'            => $opd->code,
                'completion_rate' => $tasks['completion_rate'],
                'overdue'         => $tasks['overdue'],
                'avg_skp'         => $skp['avg_final_score'],
                'active_projects' => $proj['active'],
                'avg_progress'    => $proj['avg_progress'],
            ];
        })->values()->all();
    }

    // ── Per-domain aggregates (all org-pinned COUNT/AVG) ────────────────────

    /** @return array<string, int|float> */
    private function taskMetrics(string $orgId): array
    {
        $base = DB::table('tasks')
            ->where('organization_id', $orgId)
            ->whereNull('deleted_at');

        $total       = (clone $base)->count();
        $completed   = (clone $base)->where('status', TaskStatus::COMPLETED->value)->count();
        $inProgress  = (clone $base)->where('status', TaskStatus::IN_PROGRESS->value)->count();
        $overdue     = (clone $base)
            ->whereNotNull('due_date')
            ->where('due_date', '<', Carbon::today())
            ->whereNotIn('status', self::TASK_TERMINAL)
            ->count();

        return [
            'total'           => $total,
            'completed'       => $completed,
            'overdue'         => $overdue,
            'in_progress'     => $inProgress,
            'completion_rate' => $total > 0 ? round($completed / $total * 100, 2) : 0.0,
        ];
    }

    /** @return array<string, int> */
    private function meetingMetrics(string $orgId): array
    {
        $base = DB::table('meetings')
            ->where('organization_id', $orgId)
            ->whereNull('deleted_at');

        return [
            'total'     => (clone $base)->count(),
            'completed' => (clone $base)->where('status', MeetingStatus::COMPLETED->value)->count(),
        ];
    }

    /** @return array<string, int> */
    private function documentMetrics(string $orgId): array
    {
        $base = DB::table('documents')
            ->where('organization_id', $orgId)
            ->whereNull('deleted_at');

        return [
            'total'            => (clone $base)->count(),
            'published'        => (clone $base)->where('status', DocumentStatus::PUBLISHED->value)->count(),
            'pending_approval' => (clone $base)->where('status', DocumentStatus::IN_REVIEW->value)->count(),
        ];
    }

    /** @return array<string, int> */
    private function reportMetrics(string $orgId): array
    {
        $base = DB::table('reports')
            ->where('organization_id', $orgId)
            ->whereNull('deleted_at');

        return [
            'total'     => (clone $base)->count(),
            'published' => (clone $base)->where('status', ReportStatus::PUBLISHED->value)->count(),
        ];
    }

    /** @return array<string, int|float> */
    private function projectMetrics(string $orgId): array
    {
        $base = DB::table('projects')
            ->where('organization_id', $orgId)
            ->whereNull('deleted_at');

        $total       = (clone $base)->count();
        $active      = (clone $base)->where('status', ProjectStatus::ACTIVE->value)->count();
        $avgProgress = (clone $base)->avg('progress_percent');

        return [
            'total'        => $total,
            'active'       => $active,
            'avg_progress' => $avgProgress !== null ? round((float) $avgProgress, 2) : 0.0,
        ];
    }

    /**
     * SKP aggregates: plan count, evaluated count, avg final score, and the
     * predicate distribution. Evaluations have no organization_id column, so they
     * are joined through skp_plans (which does) and pinned to the org there.
     *
     * @return array<string, mixed>
     */
    private function skpMetrics(string $orgId): array
    {
        $plans = (int) DB::table('skp_plans')
            ->where('organization_id', $orgId)
            ->whereNull('deleted_at')
            ->count();

        $evalBase = DB::table('skp_evaluations')
            ->join('skp_plans', 'skp_evaluations.skp_plan_id', '=', 'skp_plans.id')
            ->where('skp_plans.organization_id', $orgId)
            ->whereNull('skp_plans.deleted_at');

        $evaluated = (int) (clone $evalBase)->whereNotNull('skp_evaluations.final_score')->count();
        $avg       = (clone $evalBase)->avg('skp_evaluations.final_score');

        $distribution = [];
        foreach (PerformancePredicate::cases() as $predicate) {
            $distribution[$predicate->value] = (int) (clone $evalBase)
                ->where('skp_evaluations.predicate', $predicate->value)
                ->count();
        }

        return [
            'plans'                   => $plans,
            'evaluated'               => $evaluated,
            'avg_final_score'         => $avg !== null ? round((float) $avg, 2) : 0.0,
            'predicate_distribution'  => $distribution,
        ];
    }

    /** @return array<string, int> */
    private function userMetrics(string $orgId): array
    {
        $active = (int) DB::table('users')
            ->where('organization_id', $orgId)
            ->where('status', \App\Enums\UserStatus::ACTIVE->value)
            ->whereNull('deleted_at')
            ->count();

        return ['active' => $active];
    }

    /** @return array<string, int> */
    private function notificationMetrics(string $orgId): array
    {
        $sent = (int) DB::table('app_notifications')
            ->where('organization_id', $orgId)
            ->whereIn('status', [
                NotificationStatus::SENT->value,
                NotificationStatus::DELIVERED->value,
                NotificationStatus::READ->value,
            ])
            ->count();

        return ['sent' => $sent];
    }
}
